### ISSUE TITLE
Problem with Powershell Security

### ISSUE THREAD

**Issue by RealDefender** [danogitsit/MO497128-Microsoft-Defender-ASR-Issue-Fixer#1]
Hi. Thanks for the script. But please change the [Environment]::GetFolderPath("Desktop") to "$env:USERPROFILE+"\Desktop" (would be blocked when constrained language mode is enabled)

**Comment by danogitsit** [comment]
Hi @RealDefender this method was put in as it supports fetching redirected Desktops, whilst it could be replaced by grabbing the the desktop location from regkey (which would support redirected desktops), the method used to create shortcuts (not natively built in to PS) uses a COM object which is also blocked in constrained language mode. I have updated the README to say CLM is not supported as a result. I will keep looking to see if there is another method to create shortcuts without COM but Microsoft also using this method in their own script.
